# Generated by Django 4.2.5 on 2023-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumbre', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='datetime',
            field=models.TimeField(verbose_name='Время, когда необходимо выполнять привычку'),
        ),
    ]
