# Generated by Django 4.2.5 on 2023-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumbre', '0003_alter_habits_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='related_Habit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Привычка которая связана с другой, но не для приятных'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='reward',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Вознаграждение'),
        ),
    ]
