# Generated by Django 4.2.5 on 2023-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumbre', '0004_alter_habits_related_habit_alter_habits_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='periodicity',
            field=models.IntegerField(verbose_name='Периодичность выполнения привычки для напоминания в днях.'),
        ),
    ]
