# Generated by Django 4.2.5 on 2023-10-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumbre', '0008_habits_time_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habits',
            name='time_to_complete',
        ),
    ]
