# Generated by Django 4.2.5 on 2023-10-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumbre', '0009_remove_habits_time_to_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='next_repost',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следуйщей отправки'),
        ),
    ]
