# Generated by Django 4.2.5 on 2023-10-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumbre', '0010_habits_next_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='next_repost',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следуйщей отправки, этот параметр автоматический , не изменять!!!'),
        ),
    ]
