# Generated by Django 4.2.5 on 2023-10-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumbre', '0011_alter_habits_next_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='datetime',
            field=models.TimeField(verbose_name='Время, когда нужно делать привычку'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='next_repost',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следуйщей отправки, не изменять!'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='related_Habit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Привычка, но не для приятных'),
        ),
    ]
